package com.sabrepenguin.techreborn.datagen.builders;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.sabrepenguin.techreborn.datagen.builders.ingredients.ItemIngredient;
import net.minecraft.item.ItemStack;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;

public class FurnaceBuilder<T extends FurnaceBuilder<T>> extends AbstractBuilder<T> {
	protected List<ItemIngredient> ingredients = new ArrayList<>();
	protected float experience = 1.0f;

	public FurnaceBuilder() {
		this.withType("techreborn:smelt");
	}

	public T withInput(ItemStack input) {
		ingredients.add(new ItemIngredient(input));
		return getThis();
	}

	public T withExperience(float experience) {
		this.experience = experience;
		return getThis();
	}

	@Override
	public String save(File folder) {
		if (!folder.exists()) {
			if (!folder.mkdirs())
				throw new RuntimeException("Unable to make directories");
		}
		if (this.result == null)
			throw new RuntimeException("Does not have a result");
		try (Writer writer = new FileWriter(new File(folder, name))) {
			GSON.toJson(this, writer);
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		return "";
	}

	@Override
	@SuppressWarnings("unchecked")
	protected T getThis() {
		return (T) this;
	}

	public static class FurnaceBuilderSerializer<T extends FurnaceBuilder<T>> implements JsonSerializer<FurnaceBuilder<T>> {

		@Override
		public JsonElement serialize(FurnaceBuilder<T> src, Type typeOfSrc, JsonSerializationContext context) {
			JsonObject element = new JsonObject();
			element.addProperty("__comment", "Generated by FurnaceBuilder.java");
			element.addProperty("type", src.type);
			element.add("ingredients", context.serialize(src.ingredients));
			element.add("result", context.serialize(src.result));
			element.addProperty("experience", src.experience);
			return element;
		}
	}
}
