package com.sabrepenguin.techreborn.datagen.builders;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.sabrepenguin.techreborn.datagen.builders.ingredients.ReplaceableIngredient;
import net.minecraft.item.ItemStack;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.lang.reflect.Type;

public class ReplaceableShapedBuilder<T extends ReplaceableShapedBuilder<T>> extends ShapedBuilder<T> {

	protected ReplaceableIngredient result;

	public ReplaceableShapedBuilder() {
		super();
		this.withType("techreborn:replaceable_shaped");
	}

	public T define(char key, ItemStack original, ItemStack replacement) {
		ingredients.put(key, new ReplaceableIngredient(original, replacement));
		return self();
	}

	public T withOutput(ReplaceableIngredient output) {
		this.result = output;
		return self();
	}

	@Override
	@SuppressWarnings("unchecked")
	protected T getThis() {
		return (T) this;
	}

	@Override
	public String save(File folder) {
		checkRecipe();
		if (!folder.exists()) {
			if (!folder.mkdirs())
				throw new RuntimeException("Unable to make directories");
		}
		try (Writer writer = new FileWriter(new File(folder, name))) {
			GSON.toJson(this, writer);
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		return "";
	}

	public static class ReplaceableShapedBuilderSerializer<T extends ReplaceableShapedBuilder<T>> implements JsonSerializer<ReplaceableShapedBuilder<T>> {

		@Override
		public JsonElement serialize(ReplaceableShapedBuilder src, Type typeOfSrc, JsonSerializationContext context) {
			JsonObject obj = new JsonObject();
			obj.addProperty("__comment", "Generated by ReplaceableShapedBuilder.java");
			obj.addProperty("type", src.type);
			obj.add("pattern", context.serialize(src.pattern));
			obj.add("key", context.serialize(src.ingredients));
			obj.add("result", context.serialize(src.result));
			return obj;
		}
	}
}
