package com.sabrepenguin.techreborn.datagen.builders;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.sabrepenguin.techreborn.datagen.builders.ingredients.IBasicIngredient;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.lang.reflect.Type;

public class ReplaceableShapelessBuilder<T extends ReplaceableShapelessBuilder<T>> extends ShapelessBuilder<T> {
	protected IBasicIngredient result;

	public T withOutput(IBasicIngredient output) {
		this.result = output;
		return self();
	}

	@Override
	public String save(File folder) {
		if (!folder.exists()) {
			if (!folder.mkdirs())
				throw new RuntimeException("Unable to make directories");
		}
		try (Writer writer = new FileWriter(new File(folder, name))) {
			GSON.toJson(this, writer);
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		return "";
	}

	public static class ReplaceableShapelessBuilderSerializer<T extends ReplaceableShapelessBuilder<T>> implements JsonSerializer<ReplaceableShapelessBuilder<T>> {

		@Override
		public JsonElement serialize(ReplaceableShapelessBuilder src, Type typeOfSrc, JsonSerializationContext context) {
			JsonObject obj = new JsonObject();
			obj.addProperty("__comment", "Generated by ReplaceableShapedBuilder.java");
			if (!src.conditions.isEmpty())
				obj.add("conditions", context.serialize(src.conditions));
			obj.addProperty("type", src.type);
			obj.add("ingredients", context.serialize(src.ingredients));
			obj.add("result", context.serialize(src.result));
			return obj;
		}
	}
}
