package com.sabrepenguin.techreborn.datagen.builders;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.sabrepenguin.techreborn.datagen.builders.ingredients.IBasicIngredient;
import com.sabrepenguin.techreborn.datagen.builders.ingredients.ItemIngredient;
import com.sabrepenguin.techreborn.datagen.builders.ingredients.OreDictIngredient;
import net.minecraft.item.ItemStack;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.lang.reflect.Type;
import java.util.*;
import java.util.stream.Collectors;

public class ShapedBuilder<T extends ShapedBuilder<T>> extends AbstractBuilder<T> {
	protected List<String> pattern = new ArrayList<>();
	protected Map<Character, IBasicIngredient> ingredients = new HashMap<>();

	public ShapedBuilder() {
		this.withType("minecraft:crafting_shaped");
	}

	public T pattern(String pattern) {
		if (this.pattern.size() >= 3)
			throw new RuntimeException("Attempted to add fourth row to basic crafting shaped pattern");
		if (pattern.length() > 3)
			throw new RuntimeException("Recipe row too long: " + pattern);
		this.pattern.add(pattern);
		return self();
	}

	public T define(char key, ItemStack ingredient) {
		ingredients.put(key, new ItemIngredient(ingredient));
		return self();
	}

	public T define(char key, String oreDict) {
		return define(key, oreDict, 1);
	}

	public T define(char key, String oreDict, int count) {
		ingredients.put(key, new OreDictIngredient(oreDict, count));
		return self();
	}

	public T define(char key, IBasicIngredient ingredient) {
		ingredients.put(key, ingredient);
		return self();
	}

	@Override
	@SuppressWarnings("unchecked")
	protected T getThis() {
		return (T) this;
	}

	protected void checkRecipe() {
		Set<Character> checkedChars = new HashSet<>(ingredients.keySet());
		for (String p: pattern) {
			if (p.length() > 3)
				throw new RuntimeException("Pattern length cannot be larger than 3");
			for (char c: p.toCharArray()) {
				if (!ingredients.containsKey(c) && c != ' ') {
					throw new RuntimeException("No ingredient for key " + c);
				}
				checkedChars.remove(c);
			}
		}
		if (!checkedChars.isEmpty())
			throw new RuntimeException("Unused keys: " + checkedChars.stream().map(Object::toString).collect(Collectors.joining(", ")));
	}

	@Override
	public String save(File folder) {
		checkRecipe();
		if (!folder.exists()) {
			if (!folder.mkdirs())
				throw new RuntimeException("Unable to make directories");
		}
		try (Writer writer = new FileWriter(new File(folder, name))) {
			GSON.toJson(this, writer);
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		return "";
	}

	public static class ShapedBuilderSerializer<T extends ShapedBuilder<T>> implements JsonSerializer<ShapedBuilder<T>> {

		@Override
		public JsonElement serialize(ShapedBuilder src, Type typeOfSrc, JsonSerializationContext context) {
			JsonObject obj = new JsonObject();
			obj.addProperty("__comment", "Generated by ShapedBuilder.java");
			obj.addProperty("type", src.type);
			obj.add("pattern", context.serialize(src.pattern));
			obj.add("key", context.serialize(src.ingredients));
			obj.add("result", context.serialize(src.result));
			return obj;
		}
	}
}
