package com.sabrepenguin.techreborn.datagen.builders;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import net.minecraft.item.ItemStack;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;

public class ShapelessBuilder extends AbstractBuilder<ShapelessBuilder> {
	protected List<AbstractBuilder.BasicIngredient> ingredients = new ArrayList<>();

	public ShapelessBuilder() {
		this.withType("minecraft:crafting_shapeless");
	}

	public ShapelessBuilder requires(String oredict) {
		ingredients.add(new Oredict(oredict, 1));
		return self();
	}

	public ShapelessBuilder requires(ItemStack stack) {
		ingredients.add(new ItemIng(stack));
		return self();
	}

	@Override
	public String save(File folder) {
		if (!folder.exists()) {
			if (!folder.mkdirs())
				throw new RuntimeException("Unable to make directories");
		}
		try (Writer writer = new FileWriter(new File(folder, name))) {
			GSON.toJson(this, writer);
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		return "";
	}

	public static class ShapelessBuilderSerializer implements JsonSerializer<ShapelessBuilder> {

		@Override
		public JsonElement serialize(ShapelessBuilder src, Type typeOfSrc, JsonSerializationContext context) {
			JsonObject obj = new JsonObject();
			obj.addProperty("__comment", "Generated by ShapelessBuilder.java");
			obj.addProperty("type", src.type);
			obj.add("ingredients", context.serialize(src.ingredients));
			obj.add("result", context.serialize(src.result));
			return obj;
		}
	}
}
