package com.sabrepenguin.techreborn.datagen.builders;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.sabrepenguin.techreborn.datagen.builders.ingredients.IBasicIngredient;
import com.sabrepenguin.techreborn.datagen.builders.ingredients.ItemIngredient;
import com.sabrepenguin.techreborn.datagen.builders.ingredients.OreDictIngredient;
import net.minecraft.item.ItemStack;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.List;

public class ShapelessBuilder<T extends ShapelessBuilder<T>> extends AbstractBuilder<T> {
	protected List<IBasicIngredient> ingredients = new ArrayList<>();

	public ShapelessBuilder() {
		this.withType("minecraft:crafting_shapeless");
	}

	public T requires(String oredict) {
		ingredients.add(new OreDictIngredient(oredict, 1));
		return self();
	}

	public T requires(ItemStack stack) {
		ingredients.add(new ItemIngredient(stack));
		return self();
	}

	public T requires(IBasicIngredient ingredient) {
		ingredients.add(ingredient);
		return self();
	}

	@Override
	@SuppressWarnings("unchecked")
	protected T getThis() {
		return (T) this;
	}

	@Override
	public String save(File folder) {
		if (!folder.exists()) {
			if (!folder.mkdirs())
				throw new RuntimeException("Unable to make directories");
		}
		try (Writer writer = new FileWriter(new File(folder, name))) {
			GSON.toJson(this, writer);
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		return "";
	}

	public static class ShapelessBuilderSerializer<T extends ShapelessBuilder<T>> implements JsonSerializer<ShapelessBuilder<T>> {

		@Override
		public JsonElement serialize(ShapelessBuilder src, Type typeOfSrc, JsonSerializationContext context) {
			JsonObject obj = new JsonObject();
			obj.addProperty("__comment", "Generated by ShapelessBuilder.java");
			if (!src.conditions.isEmpty())
				obj.add("conditions", context.serialize(src.conditions));
			obj.addProperty("type", src.type);
			obj.add("ingredients", context.serialize(src.ingredients));
			obj.add("result", context.serialize(src.result));
			return obj;
		}
	}
}
