package com.sabrepenguin.techreborn.datagen.builders;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import net.minecraft.item.ItemStack;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

public class ShapedBuilder extends AbstractBuilder<ShapedBuilder> {
	protected String[] pattern = new String[3];
	private transient int index = 0;
	protected Map<Character, AbstractBuilder.BasicIngredient> ingredients = new HashMap<>();

	public ShapedBuilder() {
		this.withType("minecraft:crafting_shaped");
	}

	public ShapedBuilder pattern(String pattern) {
		if (index >= 3)
			throw new RuntimeException("Attempted to add fourth row to basic crafting shaped pattern");
		this.pattern[index] = pattern;
		index++;
		return self();
	}

	public ShapedBuilder define(char key, ItemStack ingredient) {
		ingredients.put(key, new ItemIng(ingredient));
		return self();
	}

	public ShapedBuilder define(char key, String oreDict) {
		return define(key, oreDict, 1);
	}

	public ShapedBuilder define(char key, String oreDict, int count) {
		ingredients.put(key, new Oredict(oreDict, count));
		return this;
	}

	@Override
	public String save(File folder) {
		Set<Character> checkedChars = new HashSet<>(ingredients.keySet());
		for (String p: pattern) {
			if (p.length() > 3)
				throw new RuntimeException("Pattern length cannot be larger than 3");
			for (char c: p.toCharArray()) {
				if (!ingredients.containsKey(c)) {
					throw new RuntimeException("No ingredient for key " + c);
				}
				checkedChars.remove(c);
			}
		}
		if (!checkedChars.isEmpty())
			throw new RuntimeException("Unused keys: " + checkedChars.stream().map(Object::toString).collect(Collectors.joining(", ")));

		try (Writer writer = new FileWriter(new File(folder, name))) {
			GSON.toJson(this, writer);
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		return "";
	}

	public static class ShapedBuilderSerializer implements JsonSerializer<ShapedBuilder> {

		@Override
		public JsonElement serialize(ShapedBuilder src, Type typeOfSrc, JsonSerializationContext context) {
			JsonObject obj = new JsonObject();
			obj.addProperty("__comment", "Generated by ShapedBuilder.java");
			obj.addProperty("type", src.type);
			obj.add("pattern", context.serialize(src.pattern));
			obj.add("key", context.serialize(src.ingredients));
			obj.add("result", context.serialize(src.result));
			return obj;
		}
	}
}
