import os
from pathlib import Path

BASE = Path("src/main/resources/assets/techreborn")
ITEM_MODELS = BASE.joinpath("models/item")
ITEM_TEXTURES = BASE.joinpath("textures/items")
INGOTS = [
    "advanced_alloy",
    "aluminum",
    "brass",
    "bronze",
    "chrome",
    "copper",
    "cupro_nickel",
    "electrum",
    "hot_tungstensteel",
    "invar",
    "iridium_alloy",
    "iridium",
    "lead",
    "mixed_metal",
    "nickel",
    "platinum",
    "plutonium",
    "refined_iron",
    "silver",
    "steel",
    "thorium",
    "tin",
    "titanium",
    "tungsten",
    "tungstensteel",
    "uranium",
    "zinc",
]
DUSTS = [
    "almandine",
    "aluminum",
    "andesite",
    "andradite",
    "ashes",
    "basalt",
    "bauxite",
    "brass",
    "bronze",
    "calcite",
    "charcoal",
    "chrome",
    "cinnabar",
    "clay",
    "coal",
    "copper",
    "dark_ashes",
    "diamond",
    "diorite",
    "dust",
    "electrum",
    "emerald",
    "ender_eye",
    "ender_pearl",
    "endstone",
    "flint",
    "galena",
    "gold",
    "granite",
    "grossular",
    "invar",
    "iridium",
    "iron",
    "lazurite",
    "lead",
    "magnesium",
    "manganese",
    "marble",
    "netherrack",
    "nickel",
    "obsidian",
    "olivine",
    "peridot",
    "phosphorous",
    "platinum",
    "plutonium",
    "pyrite",
    "pyrope",
    "red_garnet",
    "ruby",
    "saltpeter",
    "sapphire",
    "saw_dust",
    "silver",
    "sodalite",
    "spessartine",
    "sphalerite",
    "steel",
    "sulfur",
    "thorium",
    "tin",
    "titanium",
    "tungsten",
    "uranium",
    "uvarovite",
    "yellow_garnet",
    "zinc"
]
SMALL_DUSTS = [
    "almandine",
    "aluminum",
    "andesite",
    "andradite",
    "ashes",
    "basalt",
    "bauxite",
    "brass",
    "bronze",
    "calcite",
    "charcoal",
    "chrome",
    "cinnabar",
    "clay",
    "coal",
    "copper",
    "dark_ashes",
    "diamond",
    "diorite",
    "electrum",
    "emerald",
    "ender_eye",
    "ender_pearl",
    "endstone",
    "flint",
    "galena",
    "glowstone",
    "gold",
    "granite",
    "grossular",
    "invar",
    "iridium",
    "iron",
    "lazurite",
    "lead",
    "magnesium",
    "manganese",
    "marble",
    "netherrack",
    "nickel",
    "obsidian",
    "olivine",
    "peridot",
    "phosphorous",
    "platinum",
    "plutonium",
    "pyrite",
    "pyrope",
    "red_garnet",
    "redstone",
    "ruby",
    "saltpeter",
    "sapphire",
    "saw_dust",
    "silver",
    "sodalite",
    "spessartine",
    "sphalerite",
    "steel",
    "sulfur",
    "thorium",
    "tin",
    "titanium",
    "tungsten",
    "uranium",
    "uvarovite",
    "yellow_garnet",
    "zinc"
]

def image_exists(path) -> bool:
    return os.path.exists(path)

def basic_generated(image) -> str:
    return (
        f"{{\n"
        f'    "__comment": "Generated by generateResources.py",\n'
        f'    "parent": "item/generated",\n'
        f'    "textures": {{\n'
        f'        "layer0": "techreborn:{image}"\n'
        f"    }}\n"
        f"}}"
    )

def path_image(path: str, image: str) -> str:
    return (
        f"{{\n"
        f'    "__comment": "Generated by generateResources.py",\n'
        f'    "parent": "item/generated",\n'
        f'    "textures": {{\n'
        f'        "layer0": "techreborn:{path}/{image}"\n'
        f"    }}\n"
        f"}}"
    )


# INGOT creation
def create_ingots():
    ingot_model = ITEM_MODELS.joinpath("ingot")
    ingot_textures = ITEM_TEXTURES.joinpath("ingot")
    if not os.path.exists(ingot_model):
        os.makedirs(ingot_model, True)

    for ingot in INGOTS:
        new_file = ingot_model.joinpath(f"{ingot}_ingot.json")
        if not os.path.exists(ingot_model.joinpath(f"{ingot}_ingot.json")):
            image = str(ingot_textures) + f"/{ingot}_ingot"
            if not image_exists(image + ".png"):
                print(f"Error: image {image}.png doesn't exist")
                continue
            with open(new_file, "w") as file:
                file.write(basic_generated(f"items/ingot/{ingot}_ingot"))

# Dust creation
def create_dust():
    dust_model = ITEM_MODELS.joinpath("dust")
    dust_textures = ITEM_TEXTURES.joinpath("dust")
    if not os.path.exists(dust_model):
        os.makedirs(dust_model, True)

    for dust in DUSTS:
        name = "dust" if dust == "dust" else f"{dust}_dust"
        new_file = dust_model.joinpath(f"{name}.json")
        if not os.path.exists(new_file):
            image = str(dust_textures) + f"/{name}"
            if not image_exists(image + ".png"):
                print(f"Error: image {image}.png doesn't exist")
                continue
            with open(new_file, "w") as file:
                file.write(basic_generated(f"items/dust/{name}"))

# Smalldust creation
def create_smalldust():
    smalldust_model = ITEM_MODELS.joinpath("smalldust")
    smalldust_textures = ITEM_TEXTURES.joinpath("smalldust")
    if not os.path.exists(smalldust_model):
        os.makedirs(smalldust_model, True)

    for dust in SMALL_DUSTS:
        new_file = smalldust_model.joinpath(f"{dust}_smalldust.json")
        if not os.path.exists(new_file):
            image = str(smalldust_textures) + f"/{dust}_smalldust"
            if not image_exists(image + ".png"):
                print(f"Error: image {image}.png doesn't exist")
                continue
            with open(new_file, "w") as file:
                file.write(basic_generated(f"items/smalldust/{dust}_smalldust"))

if __name__ == "__main__":
    create_ingots()
    create_dust()
    create_smalldust()