import os
import json
from pathlib import Path

import recipes

OVERWRITE = True
MODID = "techreborn"
BASE = Path("src/main/resources/assets/techreborn")
RECIPES = BASE.joinpath("recipes")
ITEM_MODELS = BASE.joinpath("models/item")
ITEM_TEXTURES = BASE.joinpath("textures/items")
INGOTS = {
    "aluminum": 0,
    "brass": 1,
    "bronze": 2,
    "chrome": 3,
    "copper": 4,
    "electrum": 5,
    "invar": 6,
    "iridium": 7,
    "lead": 8,
    "nickel": 9,
    "platinum": 10,
    "silver": 11,
    "steel": 12,
    "tin": 13,
    "titanium": 14,
    "tungsten": 15,
    "hot_tungstensteel": 16,
    "tungstensteel": 17,
    "zinc": 18,
    "refined_iron": 19,
    "advanced_alloy": 20,
    "mixed_metal": 21,
    "iridium_alloy": 22,
    "thorium": 23,
    "uranium": 24,
    "plutonium": 25,
    # "cupro_nickel": 26,
}
NUGGETS = {
    "aluminum": 0,
    "brass": 1,
    "bronze": 2,
    "chrome": 3,
    "copper": 4,
    "electrum": 5,
    "invar": 6,
    "iridium": 7,
    "lead": 8,
    "nickel": 9,
    "platinum": 10,
    "silver": 11,
    "steel": 12,
    "tin": 13,
    "titanium": 14,
    "tungsten": 15,
    "hot_tungstensteel": 16,
    "tungstensteel": 17,
    "zinc": 18,
    "refined_iron": 19,
    # ItemHelper.META_PLACEHOLDER: 20,
    # ItemHelper.META_PLACEHOLDER: 21,
    # ItemHelper.META_PLACEHOLDER: 22,
    "iron": 23,
    "diamond": 24,
}
DUSTS = {
    "almandine": 0,
    "aluminum": 1,
    "andradite": 2,
    "ashes": 3,
    "basalt": 4,
    "bauxite": 5,
    "brass": 6,
    "bronze": 7,
    "calcite": 8,
    "charcoal": 9,
    "chrome": 10,
    "cinnabar": 11,
    "clay": 12,
    "coal": 13,
    "copper": 14,
    "dark_ashes": 15,
    "diamond": 16,
    "electrum": 17,
    "emerald": 18,
    "ender_eye": 19,
    "ender_pearl": 20,
    "endstone": 21,
    "flint": 22,
    "galena": 23,
    "gold": 24,
    "grossular": 25,
    "invar": 26,
    "iron": 27,
    "lazurite": 28,
    "lead": 29,
    "magnesium": 30,
    "manganese": 31,
    "marble": 32,
    "netherrack": 33,
    "nickel": 34,
    "obsidian": 35,
    "peridot": 36,
    "phosphorous": 37,
    "platinum": 38,
    "pyrite": 39,
    "pyrope": 40,
    "red_garnet": 41,
    # META_PLACEHOLDER: 42,
    "ruby": 43,
    "saltpeter": 44,
    "sapphire": 45,
    "saw_dust": 46,
    "silver": 47,
    "sodalite": 48,
    "spessartine": 49,
    "sphalerite": 50,
    "steel": 51,
    "sulfur": 52,
    "tin": 53,
    "titanium": 54,
    "tungsten": 55,
    "uvarovite": 56,
    # META_PLACEHOLDER: 57,
    "yellow_garnet": 58,
    "zinc": 59,
    # META_PLACEHOLDER: 60,
    "andesite": 61,
    "diorite": 62,
    "granite": 63,
    "iridium": 64,
    "thorium": 65,
    "uranium": 66,
    "plutonium": 67,
}
SMALL_DUSTS = {
    "almandine": 0,
    "aluminum": 1,
    "andradite": 2,
    "ashes": 3,
    "basalt": 4,
    "bauxite": 5,
    "brass": 6,
    "bronze": 7,
    "calcite": 8,
    "charcoal": 9,
    "chrome": 10,
    "cinnabar": 11,
    "clay": 12,
    "coal": 13,
    "copper": 14,
    "dark_ashes": 15,
    "diamond": 16,
    "electrum": 17,
    "emerald": 18,
    "ender_eye": 19,
    "ender_pearl": 20,
    "endstone": 21,
    "flint": 22,
    "galena": 23,
    "gold": 24,
    "grossular": 25,
    "invar": 26,
    "iron": 27,
    "lazurite": 28,
    "lead": 29,
    "magnesium": 30,
    "manganese": 31,
    "marble": 32,
    "netherrack": 33,
    "nickel": 34,
    "obsidian": 35,
    "peridot": 36,
    "phosphorous": 37,
    "platinum": 38,
    "pyrite": 39,
    "pyrope": 40,
    "red_garnet": 41,
    # META_PLACEHOLDER: 42
    "ruby": 43,
    "saltpeter": 44,
    "sapphire": 45,
    "saw_dust": 46,
    "silver": 47,
    "sodalite": 48,
    "spessartine": 49,
    "sphalerite": 50,
    "steel": 51,
    "sulfur": 52,
    "tin": 53,
    "titanium": 54,
    "tungsten": 55,
    "uvarovite": 56,
    # META_PLACEHOLDER: 57,
    "yellow_garnet": 58,
    "zinc": 59,
    # META_PLACEHOLDER: 60
    "redstone": 61,
    "glowstone": 62,
    "andesite": 63,
    "diorite": 64,
    "granite": 65,
    "iridium": 66,
    "thorium": 67,
    "uranium": 68,
    "plutonium": 69,
}


def write_to_file(file_name: str | Path, recipe: str | None):
    if recipe is None:
        print(f"Unable to write to file: {file_name}")
        return
    if not os.path.exists(file_name) or OVERWRITE:
        with open(file_name, "w") as file:
            file.write(recipe)


def image_exists(path) -> bool:
    return os.path.exists(path)


def basic_generated(image) -> str:
    result = {
        "__comment": "Generated by generateResources.py",
        "parent": "item/generated",
        "textures": {"layer0": f"techreborn:{image}"},
    }
    return json.dumps(result, indent=4)


def path_image(path: str, image: str) -> str:
    result = {
        "__comment": "Generated by generateResources.py",
        "parent": "item/generated",
        "textures": {"layer0": f"techreborn:{path}/{image}"},
    }
    return json.dumps(result, indent=4)


# INGOT creation
def create_ingots():
    ingot_model = ITEM_MODELS.joinpath("ingot")
    ingot_textures = ITEM_TEXTURES.joinpath("ingot")
    if not os.path.exists(ingot_model):
        os.makedirs(ingot_model, True)

    for ingot in INGOTS:
        new_file = ingot_model.joinpath(f"{ingot}_ingot.json")
        if not os.path.exists(ingot_model.joinpath(f"{ingot}_ingot.json")):
            image = str(ingot_textures) + f"/{ingot}_ingot"
            if not image_exists(image + ".png"):
                print(f"Error: image {image}.png doesn't exist")
                continue
            with open(new_file, "w") as file:
                file.write(basic_generated(f"items/ingot/{ingot}_ingot"))


# Smalldust creation
def create_nuggets():
    nugget_model = ITEM_MODELS.joinpath("nugget")
    nugget_textures = ITEM_TEXTURES.joinpath("nugget")
    if not os.path.exists(nugget_model):
        os.makedirs(nugget_model, True)

    for dust in NUGGETS:
        new_file = nugget_model.joinpath(f"{dust}_nugget.json")
        if not os.path.exists(new_file):
            image = str(nugget_textures) + f"/{dust}_nugget"
            if not image_exists(image + ".png"):
                print(f"Error: image {image}.png doesn't exist")
                continue
            with open(new_file, "w") as file:
                file.write(basic_generated(f"items/nugget/{dust}_nugget"))


# Dust creation
def create_dust():
    dust_model = ITEM_MODELS.joinpath("dust")
    dust_textures = ITEM_TEXTURES.joinpath("dust")
    if not os.path.exists(dust_model):
        os.makedirs(dust_model, True)

    for dust in DUSTS.keys():
        name = "dust" if dust == "dust" else f"{dust}_dust"
        new_file = dust_model.joinpath(f"{name}.json")
        if not os.path.exists(new_file):
            image = str(dust_textures) + f"/{name}"
            if not image_exists(image + ".png"):
                print(f"Error: image {image}.png doesn't exist")
                continue
            with open(new_file, "w") as file:
                file.write(basic_generated(f"items/dust/{name}"))


# Smalldust creation
def create_smalldust():
    smalldust_model = ITEM_MODELS.joinpath("smalldust")
    smalldust_textures = ITEM_TEXTURES.joinpath("smalldust")
    if not os.path.exists(smalldust_model):
        os.makedirs(smalldust_model, True)

    for dust in SMALL_DUSTS.keys():
        new_file = smalldust_model.joinpath(f"{dust}_smalldust.json")
        if not os.path.exists(new_file):
            image = str(smalldust_textures) + f"/{dust}_smalldust"
            if not image_exists(image + ".png"):
                print(f"Error: image {image}.png doesn't exist")
                continue
            with open(new_file, "w") as file:
                file.write(basic_generated(f"items/smalldust/{dust}_smalldust"))


def dust_craft_creation():
    dust_crafts = RECIPES.joinpath("dust")
    if not os.path.exists(dust_crafts):
        os.makedirs(dust_crafts, True)
    for input_name in SMALL_DUSTS.keys():
        fname = dust_crafts.joinpath(f"{input_name}_dust.json")
        rinput = recipes.create_ore("dustSmall", input_name)
        mdata = DUSTS.get(input_name)
        if mdata is None:
            continue
        output = recipes.create_item(MODID, "dust", mdata, 1)
        write_to_file(fname, recipes.shaped_recipe(["XX", "XX"], {"X": rinput}, output))

    fname = dust_crafts.joinpath("glowstone_dust.json")
    rinput = recipes.create_ore("dustSmall", "glowstone")
    output = recipes.create_item("minecraft", "glowstone_dust", count=1)
    write_to_file(fname, recipes.shaped_recipe(["XX", "XX"], {"X": rinput}, output))
    fname = dust_crafts.joinpath("redstone_dust.json")
    rinput = recipes.create_ore("dustSmall", "redstone")
    output = recipes.create_item("minecraft", "redstone", count=1)
    write_to_file(fname, recipes.shaped_recipe(["XX", "XX"], {"X": rinput}, output))

    smalldust_crafts = RECIPES.joinpath("smalldust")
    if not os.path.exists(smalldust_crafts):
        os.makedirs(smalldust_crafts, True)
    for input_name in DUSTS.keys():
        fname = smalldust_crafts.joinpath(f"{input_name}_smalldust.json")
        rinput = recipes.create_ore("dust", input_name)
        mdata = SMALL_DUSTS.get(input_name)
        if mdata is None:
            continue
        output = recipes.create_item(MODID, "smalldust", mdata, 4)
        write_to_file(fname, recipes.shapeless_recipe([rinput], output))


def ingot_craft_creation():
    ingot_crafts = RECIPES.joinpath("ingot")
    if not os.path.exists(ingot_crafts):
        os.makedirs(ingot_crafts, True)
    for name in INGOTS.keys():
        fname = ingot_crafts.joinpath(f"{name}_nugget.json")
        rinput = recipes.create_ore("ingot", name)
        mdata = NUGGETS.get(name)
        if mdata is None:
            continue
        output = recipes.create_item(MODID, "nuggets", mdata, 9)
        write_to_file(fname, recipes.shapeless_recipe([rinput], output))
    fname = ingot_crafts.joinpath(f"iron_nugget.json")
    rinput = recipes.create_ore("ingot", "iron")
    mdata = NUGGETS.get("iron")
    output = recipes.create_item(MODID, "nuggets", mdata, 9)
    write_to_file(fname, recipes.shapeless_recipe([rinput], output))


if __name__ == "__main__":
    create_ingots()
    create_nuggets()
    create_dust()
    create_smalldust()
    dust_craft_creation()
    ingot_craft_creation()
