import os
from pathlib import Path

BASE = Path("src/main/resources/assets/techreborn")
ITEM_MODELS = BASE.joinpath("models/item")
INGOTS = [
    "advanced_alloy",
    "aluminum",
    "brass",
    "bronze",
    "chrome",
    "copper",
    "cupro_nickel",
    "electrum",
    "hot_tungstensteel",
    "invar",
    "iridium_alloy",
    "iridium",
    "lead",
    "mixed_metal",
    "nickel",
    "platinum",
    "plutonium",
    "refined_iron",
    "silver",
    "steel",
    "thorium",
    "tin",
    "titanium",
    "tungsten",
    "tungstensteel",
    "uranium",
    "zinc",
]


def basic_generated(image) -> str:
    return (
        f"{{\n"
        f'    "__comment": "Generated by generateResources.py",\n'
        f'    "parent": "item/generated",\n'
        f'    "textures": {{\n'
        f'        "layer0": "techreborn:{image}"\n'
        f"    }}\n"
        f"}}"
    )


# INGOT creation

ingot_model = ITEM_MODELS.joinpath("ingot")
if not os.path.exists(ingot_model):
    os.makedirs(ingot_model, True)

for ingot in INGOTS:
    new_file = ingot_model.joinpath(f"{ingot}_ingot.json")
    if not os.path.exists(ingot_model.joinpath(f"{ingot}_ingot.json")):
        with open(new_file, "w") as file:
            file.write(basic_generated(f"items/ingot/{ingot}_ingot"))
