import json

import registries

COMMENT = "Generated by generateResources.py"


def _capitalize_oredict(ore_in: str) -> str:
    words: list[str] = ore_in.split("_")
    out = ""
    for word in words:
        out = out + word.capitalize()
    return out


def create_item(modid: str, item_name: str, data: int = -1, count: int = 0) -> dict:
    """
    Helper method to create items for recipes
    :param modid: Which mod to target
    :param item_name: The item name to target
    :param data: The metadata of the item
    :param count: The output count (for outputs only)
    :return: A complete item, to be passed as output to one of the recipe methods
    """
    result: dict[str, str | int] = {
        "item": modid + ":" + item_name,
    }
    if data >= 0:
        result["data"] = data
    if count > 0:
        result["count"] = count
    return result


def create_item_output(
    modid: str, item_name: str, data: int = 0, count: int = 1
) -> dict:
    """
    Forcibly adds count to the item output.
    :param modid:
    :param item_name:
    :param data:
    :param count:
    :return:
    """
    result: dict[str, str | int] = {"item": modid + ":" + item_name, "count": count}
    if data > 0:
        result["data"] = data
    return result


def _create_ore(ore: str, count: int = 0) -> dict:
    result: dict[str, str | int] = {"type": "forge:ore_dict", "ore": ore}
    if count > 0:
        result["count"] = count
    return result


def create_ore(oretype: str, ore: str, count: int = 0) -> dict:
    return _create_ore(oretype + _capitalize_oredict(ore), count)


def validate_item(key: dict) -> bool:
    if not isinstance(key, dict):
        return False
    if key.get("item") is not None:
        return key.get("item")
    elif key.get("ore") is not None:
        return key.get("type") == "forge:ore_dict" and key.get("ore")
    return False


def validate_items(keys: dict | list) -> bool:
    if isinstance(keys, list):
        for ingredient in keys:
            if not validate_item(ingredient):
                return False
    elif isinstance(keys, dict):
        for _key, ingredient in keys.items():
            if not validate_item(ingredient):
                return False
    else:
        return False
    return True


def shaped_recipe(pattern: list[str], keys: dict, output: dict) -> str | None:
    all_keys: set[str] = set([char for row in pattern for char in row])
    for key in all_keys:
        if key != " " and key not in keys:
            return None
    if not validate_items(keys):
        return None
    result = {
        "__comment": "Generated by generateResources.py",
        "type": "minecraft:crafting_shaped",
        "pattern": pattern,
        "key": keys,
        "result": output,
    }
    return json.dumps(result, indent=4)


def furnace_recipe(
    ingredients: list, output: dict, experience: float = 0.0
) -> str | None:
    if not validate_items(ingredients):
        return None
    result: dict[str, str | list | dict | float] = {
        "__comment": COMMENT,
        "type": "techreborn:smelt",
        "inputs": ingredients,
        "result": output,
    }
    if experience > 0.0:
        result["experience"] = experience
    return json.dumps(result, indent=4)


def shapeless_recipe(ingredients: list, output: dict) -> str | None:
    return special_recipe("minecraft:crafting_shapeless", ingredients, output)


def special_recipe(
    recipe_type: str,
    ingredients: list,
    output: dict,
    recipe_time: int = 0,
    energy_cost: int = 0,
) -> str | None:
    if not (isinstance(ingredients, list)):
        return None
    if not (validate_items(ingredients)):
        return None
    result: dict[str, str | int | dict | list] = {
        "__comment": "Generated by generateResources.py",
        "type": recipe_type,
        "ingredients": ingredients,
        "result": output,
    }
    if recipe_time > 0:
        result["recipe_time"] = recipe_time
    if energy_cost > 0:
        result["fe_cost"] = energy_cost
    return json.dumps(result, indent=4)


def string_to_item(string_in: str) -> dict:
    split_words = string_in.split("#", 1)
    count = 0
    if len(split_words) == 2:
        count = int(split_words.pop(0))
    split_words = split_words[0].split(":", 1)
    modid = "minecraft"
    if len(split_words) == 2:
        modid = split_words.pop(0)
    split_words = split_words[0].split("@", 1)
    data = -1
    if len(split_words) == 2:
        data = int(split_words.pop())
    return create_item(modid, split_words[0], data, count)


def meta_string_to_item(string_in: str, registry: dict) -> dict:
    split_words = string_in.split("#", 1)
    count = 0
    if len(split_words) == 2:
        count = int(split_words.pop(0))
    split_words = split_words[0].split(":", 1)
    modid = "minecraft"
    if len(split_words) == 2:
        modid = split_words.pop(0)
    item_name = registries.get_name_for_registry(registry)
    data = registry.get(split_words[0], -1)
    return create_item(modid, item_name, data, count)


def string_to_oredict(string_in: str) -> dict:
    split_words: list[str] = string_in.split("#", 1)
    count = 0
    if len(split_words) == 2:
        count = int(split_words.pop(0))
    return _create_ore(split_words[0], count)


def test():
    assert (
        shaped_recipe(
            ["XOX", "OXO", "XOX"],
            {"X": {}},
            {"item": "item_out", "data": 3, "count": 1},
        )
        is None
    )
    assert (
        shaped_recipe(
            ["XOX", "OXO", "XOX"],
            {"X": {}, "O": {}},
            {"item": "item_out", "data": 3, "count": 1},
        )
        is None
    )
    assert (
        shaped_recipe(
            ["XOX", "OXO", "XOX"],
            {
                "X": {"type": "forge:ore_dict", "ore": "ingotIron"},
                "O": {"item": "minecraft:dirt", "data": 0},
            },
            {"item": "minecraft:stone", "data": 1, "count": 10},
        )
        is not None
    )
    assert shapeless_recipe(["Lmao"], {"item": "minecraft", "count": 1}) is None
    assert (
        shapeless_recipe(
            [
                {"type": "forge:ore_dict", "ore": "ingotIron"},
                {"item": "minecraft:dirt", "data": 0},
            ],
            {"item": "minecraft:stone", "data": 1, "count": 10},
        )
        is not None
    )

    assert create_item("minecraft", "stone", 1) == {
        "item": "minecraft:stone",
        "data": 1,
    }
    assert create_item("minecraft", "stone") == {"item": "minecraft:stone"}
    assert create_item("minecraft", "stone", 1, 15) == {
        "item": "minecraft:stone",
        "data": 1,
        "count": 15,
    }
    assert create_ore("ingot", "iron") == {"type": "forge:ore_dict", "ore": "ingotIron"}
    assert string_to_item("15#minecraft:dirt@3") == {
        "item": "minecraft:dirt",
        "data": 3,
        "count": 15,
    }
    assert string_to_item("techreborn:ingot@3") == {
        "item": "techreborn:ingot",
        "data": 3,
    }
    assert string_to_oredict("3#ingotIron") == {
        "type": "forge:ore_dict",
        "ore": "ingotIron",
        "count": 3,
    }
    assert string_to_oredict("ingotIron") == {
        "type": "forge:ore_dict",
        "ore": "ingotIron",
    }


if __name__ == "__main__":
    test()
    print(string_to_item("dirt"))
    print(string_to_oredict("ingotIron"))
    print(string_to_oredict("2#ingotIron"))


# The fun of making recipes by hand
