import json

COMMENT = "Generated by generateResources.py"


def _capitalize_oredict(ore_in: str) -> str:
    words: list[str] = ore_in.split("_")
    out = ""
    for word in words:
        out = out + word.capitalize()
    return out


def create_item(modid: str, item_name: str, data: int = -1, count: int = 0) -> dict:
    """
    Helper method to create items for recipes
    :param modid: Which mod to target
    :param item_name: The item name to target
    :param data: The metadata of the item
    :param count: The output count (for outputs only)
    :return: A complete item, to be passed as output to one of the recipe methods
    """
    result: dict[str, str | int] = {
        "item": modid + ":" + item_name,
    }
    if data >= 0:
        result["data"] = data
    if count > 0:
        result["count"] = count
    return result


def create_item_output(
    modid: str, item_name: str, data: int = 0, count: int = 1
) -> dict:
    """
    Forcibly adds count to the item output.
    :param modid:
    :param item_name:
    :param data:
    :param count:
    :return:
    """
    result: dict[str, str | int] = {"item": modid + ":" + item_name, "count": count}
    if data > 0:
        result["data"] = data
    return result


def create_ore(oretype: str, ore: str) -> dict:
    result = {"type": "forge:ore_dict", "ore": oretype + _capitalize_oredict(ore)}
    return result


def validate_item(key: dict) -> bool:
    if not isinstance(key, dict):
        return False
    if key.get("item") is not None:
        return key.get("item")
    elif key.get("ore") is not None:
        return key.get("type") == "forge:ore_dict" and key.get("ore")
    return False


def validate_items(keys: dict | list) -> bool:
    if isinstance(keys, list):
        for ingredient in keys:
            if not validate_item(ingredient):
                return False
    elif isinstance(keys, dict):
        for _key, ingredient in keys.items():
            if not validate_item(ingredient):
                return False
    else:
        return False
    return True


def shaped_recipe(pattern: list[str], keys: dict, output: dict) -> str | None:
    all_keys: set[str] = set([char for row in pattern for char in row])
    for key in all_keys:
        if key not in keys:
            return None
    if not validate_items(keys):
        return None
    result = {
        "__comment": "Generated by generateResources.py",
        "type": "minecraft:crafting_shaped",
        "pattern": pattern,
        "key": keys,
        "result": output,
    }
    return json.dumps(result, indent=4)


def furnace_recipe(
    ingredients: list, output: dict, experience: float = 0.0
) -> str | None:
    if not validate_items(ingredients):
        return None
    result: dict[str, str | list | dict | float] = {
        "__comment": COMMENT,
        "type": "techreborn:smelt",
        "inputs": ingredients,
        "result": output,
    }
    if experience > 0.0:
        result["experience"] = experience
    return json.dumps(result, indent=4)


def shapeless_recipe(ingredients: list, output: dict) -> str | None:
    return special_recipe("minecraft:crafting_shapeless", ingredients, output)


def special_recipe(
    recipe_type: str, ingredients: list, output: dict, recipe_time: int = 0
) -> str | None:
    if not (isinstance(ingredients, list)):
        return None
    if not (validate_items(ingredients)):
        return None
    result: dict[str, str | int | dict | list] = {
        "__comment": "Generated by generateResources.py",
        "type": recipe_type,
        "ingredients": ingredients,
        "result": output,
    }
    if recipe_time > 0:
        result["recipe_time"] = recipe_time
    return json.dumps(result, indent=4)


def one_to_out_oredict_to_metadata_craft(
    ore_input: str,
    output: str,
    output_metadata: int,
    count: int = 1,
) -> str:
    result = {
        "__comment": "Generated by generateResources.py",
        "type": "minecraft:crafting_shapeless",
        "ingredients": [{"type": "forge:ore_dict", "ore": ore_input}],
        "result": {"item": output, "data": output_metadata, "count": count},
    }
    return json.dumps(result, indent=4)


def test():
    assert (
        shaped_recipe(
            ["XOX", "OXO", "XOX"],
            {"X": {}},
            {"item": "item_out", "data": 3, "count": 1},
        )
        is None
    )
    assert (
        shaped_recipe(
            ["XOX", "OXO", "XOX"],
            {"X": {}, "O": {}},
            {"item": "item_out", "data": 3, "count": 1},
        )
        is None
    )
    assert (
        shaped_recipe(
            ["XOX", "OXO", "XOX"],
            {
                "X": {"type": "forge:ore_dict", "ore": "ingotIron"},
                "O": {"item": "minecraft:dirt", "data": 0},
            },
            {"item": "minecraft:stone", "data": 1, "count": 10},
        )
        is not None
    )
    assert shapeless_recipe(["Lmao"], {"item": "minecraft", "count": 1}) is None
    assert (
        shapeless_recipe(
            [
                {"type": "forge:ore_dict", "ore": "ingotIron"},
                {"item": "minecraft:dirt", "data": 0},
            ],
            {"item": "minecraft:stone", "data": 1, "count": 10},
        )
        is not None
    )

    assert create_item("minecraft", "stone", 1) == {
        "item": "minecraft:stone",
        "data": 1,
    }
    assert create_item("minecraft", "stone") == {"item": "minecraft:stone"}
    assert create_item("minecraft", "stone", 1, 15) == {
        "item": "minecraft:stone",
        "data": 1,
        "count": 15,
    }
    assert create_ore("ingot", "iron") == {"type": "forge:ore_dict", "ore": "ingotIron"}


if __name__ == "__main__":
    test()
