import json


def basic_generated(image) -> str:
    result = {
        "__comment": "Generated by generateResources.py",
        "parent": "item/generated",
        "textures": {"layer0": f"techreborn:{image}"},
    }
    return json.dumps(result, indent=4)

def block_all_model(image: str) -> str:
    result = {"parent": "block/cube_all", "textures": {"all": f"techreborn:{image}"}}
    return json.dumps(result, indent=4)