import itertools
import json

from resource.utils import *

MODID = "techreborn"


class BaseRecipeBuilder:
    def __init__(self):
        # self.name = ""
        self.recipe_type = ""

    def with_name(self, name):
        # self.name = name
        return self

    def with_type(self, recipe_type: str):
        self.recipe_type = recipe_type
        return self

    def build(self):
        # if self.name == "":
        #     raise RuntimeError("Name must not be empty")
        if self.recipe_type == "":
            raise RuntimeError("Recipe type must not be empty")


class CustomRecipeBuilder(BaseRecipeBuilder):
    def __init__(self, recipe_type: str=""):
        BaseRecipeBuilder.__init__(self)
        self.inputs: list[Ingredient] = []
        self.outputs: list[Ingredient] = []
        self.recipe_time: int = -1
        self.energy_cost: int = -1
        self.experience: float = 0
        self.with_type(recipe_type)

    def with_input(self, ingredient: Ingredient):
        self.inputs.append(ingredient)
        return self

    def with_output(self, ingredient: Ingredient):
        self.outputs.append(ingredient)
        return self

    def with_energy(self, energy: int):
        self.energy_cost = energy
        return self

    def with_time(self, time: int):
        self.recipe_time = time
        return self

    def build(self) -> str | None:
        super().build()

        if len(self.inputs) <= 0:
            raise RuntimeError("Inputs are required")
        if len(self.outputs) == 0:
            raise RuntimeError("There must be an output")

        outputs = [output.to_dict() for output in self.outputs]
        if len(outputs) == 1:
            outputs = outputs[0]

        result: dict[str, str | int | dict | list] = {
            "__comment": "Generated by recipe_builders.py",
            "type": self.recipe_type,
            "ingredients": [i.to_dict() for i in self.inputs],
            "result": outputs,
        }
        if self.recipe_time > 0:
            result["recipe_time"] = self.recipe_time
        if self.energy_cost > 0:
            result["fe_cost"] = self.energy_cost
        if self.experience > 0:
            result["experience"] = self.experience
        return json.dumps(result, indent=4)


class ShapedRecipeBuilder(BaseRecipeBuilder):
    def __init__(self):
        BaseRecipeBuilder.__init__(self)
        self.with_type("minecraft:crafting_shaped")
        self.pattern: list[str] = []
        self.keys: dict[str, Ingredient] = {}
        self.output: list[Ingredient] = []

    def with_pattern(self, pattern: list[str]):
        self.pattern = pattern
        return self

    def with_ingredient(self, key: str, ingredient: Ingredient):
        self.keys[key] = ingredient
        return self

    def with_output(self, output: Ingredient):
        self.output.append(output)
        return self

    def build(self) -> str | None:
        all_keys: set[str] = set([char for row in self.pattern for char in row])
        for key in all_keys:
            if key != " " and key not in self.keys:
                raise RuntimeError(f"Key {key} not in pattern {self.keys}")
        all_keys: dict[str, dict] = dict([(k,v.to_dict()) for k,v in self.keys.items()])
        result: dict[str, str|int|dict|list[dict]] = {
            "__comment": "Generated by recipe_builders.py",
            "type": self.recipe_type,
            "pattern": self.pattern,
            "key": all_keys,
        }
        if len(self.output) == 1:
            result["result"] = self.output[0].to_dict()
        else:
            result["result"] = [out.to_dict() for out in self.output]
        return json.dumps(result, indent=4)


class ShapelessRecipeBuilder(CustomRecipeBuilder):
    def __init__(self):
        CustomRecipeBuilder.__init__(self)
        self.with_type("minecraft:crafting_shapeless")

class FurnaceRecipeBuilder(CustomRecipeBuilder):
    def __init__(self):
        CustomRecipeBuilder.__init__(self)
        self.with_experience(1.0).with_type("techreborn:smelt")

    def with_experience(self, experience: float):
        self.experience = experience
        return self

def fluid_ingredient(fluid: str, amount: int = 1000):
    return {"type": "techreborn:fluid_container", "fluid": fluid, "amount": amount}


def validate_item(key: dict) -> bool:
    if not isinstance(key, dict):
        return False
    if key.get("item") is not None:
        return key.get("item")
    elif key.get("fluid") is not None:
        return key.get("fluid") and key.get("count") != 0
    elif key.get("ore") is not None:
        return key.get("type") == "forge:ore_dict" and key.get("ore")
    return False


def validate_items(keys: dict | list) -> bool:
    if isinstance(keys, list):
        for i in keys:
            if not validate_item(i):
                return False
    elif isinstance(keys, dict):
        for _key, i in keys.items():
            if not validate_item(i):
                return False
    else:
        return False
    return True


class Ingredient:
    def __init__(self, name: str, metadata: int = -1, item_type: str = "", count: int = 0, modid: str = "", nbt: dict = None, output: bool = False):
        if nbt is None:
            nbt = {}
        self.item_type: str = item_type
        self.count: int = count
        self.name = name
        self.metadata = metadata
        self.modid = modid
        self.output = output
        self.nbt = nbt
        self.validate()

    def get_name(self):
        return self.name

    @staticmethod
    def meta(registry: dict, item: str, count: int = 0, modid: str="techreborn") -> Ingredient:
        registry_item_base_name = registries.get_name_for_registry(registry)
        data = registry.get(item, -1)
        return Ingredient(registry_item_base_name, metadata=data, count=count, modid=modid)

    @staticmethod
    def item(normal_item: str, metadata: int = -1, count: int = 0, modid: str="minecraft") -> Ingredient:
        return Ingredient(normal_item, metadata=metadata, count=count, modid=modid)

    @staticmethod
    def mod_item(item: str, metadata: int = -1, count: int = 0, modid: str="techreborn") -> Ingredient:
        return Ingredient(item, metadata=metadata, count=count, modid=modid)

    @staticmethod
    def nbt_item(item: str, nbt: str, output: bool, metadata: int = -1, count: int = 0, modid: str="techreborn",) -> Ingredient:
        return Ingredient(item, nbt=nbt, metadata=metadata, count=count, modid=modid, item_type="minecraft:item_nbt", output=output)

    @staticmethod
    def cell(fluid: str, modid: str = "", count: int = 0):
        return Ingredient(fluid, item_type="techreborn:cell", count=count, modid=modid)

    @staticmethod
    def oredict(ore: str, oretype: str = "", count: int = 0):
        if oretype == "":
            return Ingredient(ore, item_type="forge:ore_dict", count=count)
        return Ingredient(oretype + _capitalize_oredict(ore), item_type="forge:ore_dict", count=count)

    @staticmethod
    def fluid(fluid: str, count: int = 1000, modid: str = ""):
        return Ingredient(fluid, item_type="techreborn:fluid_container", count=count, modid=modid)

    def validate(self):
        if self.item_type == "forge:ore_dict":
            if self.name == "":
                raise RuntimeError("Ore name is empty")
        elif self.item_type == "techreborn:fluid_container":
            if self.name == "":
                raise RuntimeError("Fluid ingredient name is empty")
        elif self.item_type == "techreborn:cell":
            if self.name == "":
                raise RuntimeError("No fluid in cell, did you mean to make an empty cell instead (Ingredient.mod_item)?")
        else:
            if self.name == "":
                raise RuntimeError("Ingredient name is empty")
            if self.modid == "":
                raise RuntimeError("Ingredient " + self.name + " must have a modid")

    def to_dict(self) -> dict:
        if self.item_type == "forge:ore_dict":
            result: dict[str, str|int] = {
                "type": self.item_type,
                "ore": self.name
            }
            if self.count > 0:
                result["count"] = self.count
            return result
        elif self.item_type == "techreborn:fluid_container":
            fluid = self.name
            if self.modid != "":
                fluid = self.modid + ":" + self.name
            return {
                "type": self.item_type,
                "fluid":  fluid,
                "amount": self.count
            }
        elif self.item_type == "techreborn:cell":
            fluid = self.name
            if self.modid != "":
                fluid = self.modid + ":" + self.name
            return {
                "type": self.item_type,
                "fluid": fluid,
            }
        else:
            result: dict[str, str|int] = {}
            if self.item_type == "minecraft:item_nbt" and not self.output:
                result["type"] = self.item_type
            result["item"] = self.modid + ":" + self.name
            if self.metadata >= 0:
                result["data"] = self.metadata
            if self.count > 0:
                result["count"] = self.count
            if self.item_type == "minecraft:item_nbt" and isinstance(self.nbt, dict):
                result["nbt"] = self.nbt
            return result

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=4)

def _capitalize_oredict(ore_in: str) -> str:
    words: list[str] = ore_in.split("_")
    out = ""
    for word in words:
        out = out + word.capitalize()
    return out

class RecipeMultiplier:
    def __init__(self, name, recipe_builder):
        self.inputs: list[list[Ingredient]] = []
        self.name = name
        if isinstance(recipe_builder, ShapedRecipeBuilder):
            raise RuntimeError("Ore Dict Multiplier does not implement ShapedRecipeBuilder helper")
        if isinstance(recipe_builder, BaseRecipeBuilder):
            self.recipe = recipe_builder
        else:
            raise RuntimeError("Recipe builder does not inherit BaseRecipeBuilder!")

    def add_inputs(self, ingredient: list[Ingredient]):
        self.inputs.append(ingredient)
        return self

    def run_build(self) -> dict:
        output = {}
        for combination in itertools.product(*self.inputs):
            if isinstance(self.recipe, CustomRecipeBuilder):
                self.recipe.inputs = []
                new_name = self.name + "_"
                ingredient: Ingredient
                for ingredient in combination:
                    self.recipe.with_input(ingredient)
                    new_name += ingredient.get_name()[0]
                output[new_name] = self.recipe.build()
            else:
                raise RuntimeError("Not yet implemented on this object")
        return output