import json

from resource.utils import *

MODID = "techreborn"


class BaseRecipeBuilder:
    def __init__(self):
        # self.name = ""
        self.recipe_type = ""

    def with_name(self, name):
        # self.name = name
        return self

    def with_type(self, recipe_type: str):
        self.recipe_type = recipe_type
        return self

    def build(self):
        # if self.name == "":
        #     raise RuntimeError("Name must not be empty")
        if self.recipe_type == "":
            raise RuntimeError("Recipe type must not be empty")


class CustomRecipeBuilder(BaseRecipeBuilder):
    def __init__(self):
        BaseRecipeBuilder.__init__(self)
        self.inputs: list[dict] = []
        self.outputs: list[dict] = []
        self.recipe_time: int = -1
        self.energy_cost: int = -1

    def with_input(
        self,
        registry: dict = None,
        ore_dict: str = "",
        meta_item: str = "",
        item: str = "",
        fluid: str = "",
        count: int = 0,
    ):
        if len(ore_dict) > 0:
            self.inputs.append(string_to_oredict(ore_dict, count))
        elif len(fluid) > 0:
            if count == 0:
                raise RuntimeError("Cannot have 0 for fluid amount")
            self.inputs.append(fluid_ingredient(fluid, count))
        elif len(meta_item) > 0 and registry is not None:
            if ":" not in meta_item:
                meta_item = MODID + ":" + meta_item
            self.inputs.append(meta_string_to_item(meta_item, registry, count))
        elif len(item) > 0:
            self.inputs.append(string_to_item(item, count))
        return self

    def with_output(
        self,
        registry: dict = None,
        meta_item: str = "",
        item: str = "",
        count: int = 0,
    ):
        if len(meta_item) > 0 and registry is not None:
            if ":" not in meta_item:
                meta_item = MODID + ":" + meta_item
            self.outputs.append(meta_string_to_item(meta_item, registry, count))
        elif len(item) > 0:
            self.outputs.append(string_to_item(item, count))
        return self

    def with_energy(self, energy: int):
        self.energy_cost = energy
        return self

    def with_time(self, time: int):
        self.recipe_time = time
        return self

    def build(self) -> str | None:
        super().build()

        if not (validate_items(self.inputs)):
            return None
        if len(self.inputs) <= 0:
            raise RuntimeError("Inputs are required")
        if len(self.outputs) == 0:
            raise RuntimeError("There must be an output")

        output = self.outputs
        if len(self.outputs) == 1:
            output = self.outputs[0]

        result: dict[str, str | int | dict | list] = {
            "__comment": "Generated by generateResources.py",
            "type": self.recipe_type,
            "ingredients": self.inputs,
            "result": output,
        }
        if self.recipe_time > 0:
            result["recipe_time"] = self.recipe_time
        if self.energy_cost > 0:
            result["fe_cost"] = self.energy_cost
        return json.dumps(result, indent=4)


class ShapedRecipeBuilder(BaseRecipeBuilder):
    def __init__(self):
        BaseRecipeBuilder.__init__(self)
        self.with_type("minecraft:crafting_shaped")
        self.pattern: list[str] = []
        self.keys: dict = {}
        self.output: dict = {}

    def with_pattern(self, pattern: list[str]):
        self.pattern = pattern
        return self

    def with_input(
        self,
        key: str,
        registry: dict = None,
        ore_dict: str = "",
        meta_item: str = "",
        item: str = "",
        fluid: str = "",
        count: int = 0,
    ):
        if len(ore_dict) > 0:
            self.keys[key] = string_to_oredict(ore_dict, count)
        elif len(fluid) > 0:
            if count == 0:
                raise RuntimeError("Cannot have 0 for fluid amount")
            self.keys[key] = fluid_ingredient(fluid, count)
        elif len(meta_item) > 0 and registry is not None:
            if ":" not in meta_item:
                meta_item = MODID + ":" + meta_item
            self.keys[key] = meta_string_to_item(meta_item, registry, count)
        elif len(item) > 0:
            self.keys[key] = string_to_item(item, count)
        return self

    def with_output(
        self,
        registry: dict = None,
        meta_item: str = "",
        item: str = "",
        count: int = 0,
    ):
        if len(meta_item) > 0 and registry is not None:
            if ":" not in meta_item:
                meta_item = MODID + ":" + meta_item
            self.output = meta_string_to_item(meta_item, registry, count)
        elif len(item) > 0:
            self.output = string_to_item(item, count)
        return self

    def build(self) -> str | None:
        all_keys: set[str] = set([char for row in self.pattern for char in row])
        for key in all_keys:
            if key != " " and key not in self.keys:
                raise RuntimeError(f"Key {key} not in pattern {self.keys}")
        if not validate_items(self.keys):
            raise RuntimeError(f"Invalid keys: {self.keys}")
        result = {
            "__comment": "Generated by generateResources.py",
            "type": self.recipe_type,
            "pattern": self.pattern,
            "key": self.keys,
            "result": self.output,
        }
        return json.dumps(result, indent=4)


class ShapelessRecipeBuilder(CustomRecipeBuilder):
    def __init__(self):
        CustomRecipeBuilder.__init__(self)
        self.with_type("minecraft:crafting_shapeless")


def fluid_ingredient(fluid: str, amount: int = 1000):
    return {"type": "techreborn:fluid_container", "fluid": fluid, "amount": amount}


def validate_item(key: dict) -> bool:
    if not isinstance(key, dict):
        return False
    if key.get("item") is not None:
        return key.get("item")
    elif key.get("fluid") is not None:
        return key.get("fluid") and key.get("count") != 0
    elif key.get("ore") is not None:
        return key.get("type") == "forge:ore_dict" and key.get("ore")
    return False


def validate_items(keys: dict | list) -> bool:
    if isinstance(keys, list):
        for i in keys:
            if not validate_item(i):
                return False
    elif isinstance(keys, dict):
        for _key, i in keys.items():
            if not validate_item(i):
                return False
    else:
        return False
    return True
