package com.sabrepenguin.techreborn.datagen.recipes;

import com.sabrepenguin.techreborn.blocks.BlockCable;
import com.sabrepenguin.techreborn.blocks.TRBlocks;
import com.sabrepenguin.techreborn.blocks.fluids.TRFluids;
import com.sabrepenguin.techreborn.blocks.meta.BlockMachineFrame;
import com.sabrepenguin.techreborn.datagen.builders.ShapedBuilder;
import com.sabrepenguin.techreborn.datagen.builders.ShapelessBuilder;
import com.sabrepenguin.techreborn.datagen.builders.conditions.IC2Condition;
import com.sabrepenguin.techreborn.datagen.builders.ingredients.CellIngredient;
import com.sabrepenguin.techreborn.datagen.builders.ingredients.ItemIngredient;
import com.sabrepenguin.techreborn.datagen.builders.ingredients.ListIngredient;
import com.sabrepenguin.techreborn.datagen.builders.ingredients.OreDictIngredient;
import com.sabrepenguin.techreborn.items.TRItems;
import com.sabrepenguin.techreborn.items.materials.Ingot;
import com.sabrepenguin.techreborn.items.materials.Part;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fluids.FluidRegistry;

import java.io.File;

public class PartRecipes {
	@SuppressWarnings("ConstantConditions")
	public static void parts(File file) {
		File generated = new File(file, "generated");
		new ShapedBuilder<>()
				.name("iridium_alloy")
				.pattern("IAI")
				.pattern("ADA")
				.pattern("IAI")
				.define('I', "ingotIridium")
				.define('A', "plateAdvancedAlloy")
				.define('D', "dustDiamond")
				.withResult(new ItemStack(TRItems.ingot, 1, Ingot.IngotMeta.iridium_alloy.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("scrap_box")
				.pattern("SSS")
				.pattern("SSS")
				.pattern("SSS")
				.define('S', new ItemStack(TRItems.part, 1, Part.PartMeta.scrap.metadata()))
				.withResult(new ItemStack(TRItems.scrapbox))
				.save(generated);
		new ShapedBuilder<>()
				.name("machine")
				.pattern("III")
				.pattern("I I")
				.pattern("III")
				.define('I', "ingotRefinedIron")
				.withResult(new ItemStack(TRBlocks.machine_frame, 1, BlockMachineFrame.Frame.BASIC.meta()))
				.save(generated);
		new ShapedBuilder<>()
				.name("advanced_machine")
				.pattern(" C ")
				.pattern("AMA")
				.pattern(" C ")
				.define('C', "plateCarbon")
				.define('A', "plateAdvancedAlloy")
				.define('M', "machineBlockBasic")
				.withResult(new ItemStack(TRBlocks.machine_frame, 1, BlockMachineFrame.Frame.ADVANCED.meta()))
				.save(generated);
		new ShapedBuilder<>()
				.name("highly_advanced_machine")
				.pattern("CTC")
				.pattern("TBT")
				.pattern("CTC")
				.define('C', "plateChrome")
				.define('T', "plateTitanium")
				.define('B', "machineBlockAdvanced")
				.withResult(new ItemStack(TRBlocks.machine_frame, 1, BlockMachineFrame.Frame.HIGHLY_ADVANCED.meta()))
				.save(generated);
		new ShapedBuilder<>()
				.name("data_storage_circuit")
				.pattern("RGR")
				.pattern("LCL")
				.pattern("EEE")
				.define('R', "dustRedstone")
				.define('G', "dustGlowstone")
				.define('L', "gemLapis")
				.define('C', "circuitBasic")
				.define('E', "plateEmerald")
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.data_storage_circuit.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("data_control_circuit")
				.pattern("ADA")
				.pattern("DID")
				.pattern("ADA")
				.define('A', "circuitAdvanced")
				.define('D', "circuitStorage")
				.define('I', "ingotIridium")
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.data_control_circuit.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("energy_flow_circuit")
				.pattern("ATA")
				.pattern("LIL")
				.pattern("ATA")
				.define('A', "circuitAdvanced")
				.define('T', "ingotTungsten")
				.define('L', "lapotronCrystal")
				.define('I', "plateIridiumAlloy")
				.withResult(new ItemStack(TRItems.part, 4, Part.PartMeta.energy_flow_circuit.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("data_orb")
				.pattern("DDD")
				.pattern("DSD")
				.pattern("DDD")
				.define('D', "circuitStorage")
				.define('S', "circuitElite")
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.data_orb.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("diamond_saw_blade")
				.pattern("DSD")
				.pattern("S S")
				.pattern("DSD")
				.define('D', "dustDiamond")
				.define('S', "ingotSteel")
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.diamond_saw_blade.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("diamond_grinding_head")
				.pattern("DSD")
				.pattern("SGS")
				.pattern("DSD")
				.define('S', "ingotSteel")
				.define('D', "dustDiamond")
				.define('G', "gemDiamond")
				.withResult(new ItemStack(TRItems.part, 2, Part.PartMeta.diamond_grinding_head.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("tungsten_grinding_head")
				.pattern("TST")
				.pattern("SBS")
				.pattern("TST")
				.define('S', "ingotSteel")
				.define('T', "ingotTungsten")
				.define('B', "blockSteel")
				.withResult(new ItemStack(TRItems.part, 2, Part.PartMeta.tungsten_grinding_head.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("computer_monitor")
				.pattern("ADA")
				.pattern("DGD")
				.pattern("ADA")
				.define('D', "dye")
				.define('A', "ingotAluminum")
				.define('G', "paneGlass")
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.computer_monitor.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("coolant_simple")
				.pattern(" T ")
				.pattern("TWT")
				.pattern(" T ")
				.define('T', "ingotTin")
				.define('W', new ListIngredient()
						.addIngredient(new ItemIngredient(new ItemStack(Items.WATER_BUCKET)))
						.addIngredient(new CellIngredient(FluidRegistry.getFluid("water"))))
				.withResult(new ItemStack(TRItems.part, 2, Part.PartMeta.coolant_simple.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("coolant_triple")
				.pattern("TTT")
				.pattern("CCC")
				.pattern("TTT")
				.define('T', "ingotTin")
				.define('C', new ItemStack(TRItems.part, 1, Part.PartMeta.coolant_simple.metadata()))
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.coolant_triple.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("coolant_six")
				.pattern("TCT")
				.pattern("TPT")
				.pattern("TCT")
				.define('T', "ingotTin")
				.define('C', new ItemStack(TRItems.part, 1, Part.PartMeta.coolant_triple.metadata()))
				.define('P', "plateCopper")
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.coolant_six.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("helium_coolant_simple")
				.pattern(" T ")
				.pattern("TCT")
				.pattern(" T ")
				.define('T', "ingotTin")
				.define('C', new CellIngredient(TRFluids.HELIUM))
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.helium_coolant_simple.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("helium_coolant_triple")
				.pattern("TTT")
				.pattern("CCC")
				.pattern("TTT")
				.define('T', "ingotTin")
				.define('C', new ItemStack(TRItems.part, 1, Part.PartMeta.helium_coolant_simple.metadata()))
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.helium_coolant_triple.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("helium_coolant_six")
				.pattern("THT")
				.pattern("TCT")
				.pattern("THT")
				.define('T', "ingotTin")
				.define('C', "ingotCopper")
				.define('H', new ItemStack(TRItems.part, 1, Part.PartMeta.helium_coolant_triple.metadata()))
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.helium_coolant_six.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("nak_coolant_simple_1")
				.pattern("TST")
				.pattern("PCP")
				.pattern("TST")
				.define('T', "ingotTin")
				.define('C', new ItemStack(TRItems.part, 1, Part.PartMeta.coolant_simple.metadata()))
				.define('S', new CellIngredient(TRFluids.SODIUM))
				.define('P', new CellIngredient(TRFluids.POTASSIUM))
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.nak_coolant_simple.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("nak_coolant_simple_2")
				.pattern("TPT")
				.pattern("SCS")
				.pattern("TPT")
				.define('T', "ingotTin")
				.define('C', new ItemStack(TRItems.part, 1, Part.PartMeta.coolant_simple.metadata()))
				.define('S', new CellIngredient(TRFluids.SODIUM))
				.define('P', new CellIngredient(TRFluids.POTASSIUM))
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.nak_coolant_simple.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("nak_coolant_triple")
				.pattern("TTT")
				.pattern("CCC")
				.pattern("TTT")
				.define('T', "ingotTin")
				.define('C', new ItemStack(TRItems.part, 1, Part.PartMeta.nak_coolant_simple.metadata()))
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.nak_coolant_triple.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("nak_coolant_six")
				.pattern("THT")
				.pattern("TCT")
				.pattern("THT")
				.define('T', "ingotTin")
				.define('C', "ingotCopper")
				.define('H', new ItemStack(TRItems.part, 1, Part.PartMeta.nak_coolant_triple.metadata()))
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.nak_coolant_six.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("super_conductor")
				.pattern("CCC")
				.pattern("TIT")
				.pattern("EEE")
				.define('E', "circuitMaster")
				.define('C', new ItemStack(TRItems.part, 1, Part.PartMeta.helium_coolant_simple.metadata()))
				.define('T', "ingotTungsten")
				.define('I', "plateIridiumAlloy")
				.withResult(new ItemStack(TRItems.part, 4, Part.PartMeta.super_conductor.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("carbon_fiber")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern(" C ")
				.pattern("C C")
				.pattern(" C ")
				.define('C', "dustCoal")
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.carbon_fiber.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("carbon_fiber_cell")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("CCC")
				.pattern("C C")
				.pattern("CCC")
				.define('C', new CellIngredient(TRFluids.CARBON))
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.carbon_fiber.metadata()))
				.save(generated);
		new ShapelessBuilder<>()
				.name("carbon_mesh")
				.withCondition(IC2Condition.DeduplicateCondition())
				.requires(new ItemStack(TRItems.part, 1, Part.PartMeta.carbon_fiber.metadata()))
				.requires(new ItemStack(TRItems.part, 1, Part.PartMeta.carbon_fiber.metadata()))
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.carbon_mesh.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("electronic_circuit")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("WWW")
				.pattern("RIR")
				.pattern("WWW")
				.define('I', "ingotRefinedIron")
				.define('R', new ItemStack(Items.REDSTONE))
				.define('W', IC2Duplicates.CABLE_ICOPPER.getIngredient())
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.electronic_circuit.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("advanced_circuit")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("RGR")
				.pattern("LCL")
				.pattern("RGR")
				.define('R', "dustRedstone")
				.define('G', "dustGlowstone")
				.define('L', "gemLapis")
				.define('C', "circuitBasic")
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.advanced_circuit.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("iridium_neutron_reflector")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("PPP")
				.pattern("PIP")
				.pattern("PPP")
				.define('P', "reflectorThick")
				.define('I', "ingotIridium")
				.withResult(new ItemStack(TRItems.iridium_neutron_reflector))
				.save(generated);
		new ShapedBuilder<>()
				.name("thick_neutron_reflector")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern(" P ")
				.pattern("PCP")
				.pattern(" P ")
				.define('P', "reflectorBasic")
				.define('C', new CellIngredient(TRFluids.BERYLLIUM))
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.thick_neutron_reflector.metadata()))
				.save(generated);
		new ShapedBuilder<>()
				.name("neutron_reflector")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("TCT")
				.pattern("CPC")
				.pattern("TCT")
				.define('T', "dustTin")
				.define('P', "plateCopper")
				.define('C', "dustCoal")
				.withResult(new ItemStack(TRItems.part, 1, Part.PartMeta.neutron_reflector.metadata()))
				.save(generated);
	}

	@SuppressWarnings("ConstantConditions")
	public static void cables(File file) {
		File cables = new File(file, "cable");
		new ShapedBuilder<>()
				.name("superconducter")
				.pattern("MFM")
				.pattern("SSS")
				.pattern("MFM")
				.define('M', new ItemStack(TRBlocks.machine_frame, 1, BlockMachineFrame.Frame.ADVANCED.meta()))
				.define('F', new ItemStack(TRItems.part, 1, Part.PartMeta.energy_flow_circuit.metadata()))
				.define('S', "craftingSuperconductor")
				.withResult(new ItemStack(TRBlocks.cable, 1, BlockCable.CableEnum.SUPERCONDUCTOR.metadata()))
				.save(cables);
		new ShapedBuilder<>()
				.name("superconducter_extra")
				.pattern("MFM")
				.pattern("SSS")
				.pattern("MFM")
				.define('M', new ItemStack(TRBlocks.machine_frame, 1, BlockMachineFrame.Frame.ADVANCED.meta()))
				.define('F', new ItemStack(TRItems.part, 1, Part.PartMeta.energy_flow_circuit.metadata()))
				.define('S', new ItemStack(TRItems.part, 1, Part.PartMeta.enhanced_super_conductor.metadata()))
				.withResult(new ItemStack(TRBlocks.cable, 8, BlockCable.CableEnum.SUPERCONDUCTOR.metadata()))
				.save(cables);
		new ShapedBuilder<>()
				.name("copper")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("CCC")
				.define('C', "ingotCopper")
				.withResult(new ItemStack(TRBlocks.cable, 6, BlockCable.CableEnum.COPPER.metadata()))
				.save(cables);
		new ShapedBuilder<>()
				.name("tin")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("TTT")
				.define('T', "ingotTin")
				.withResult(new ItemStack(TRBlocks.cable, 9, BlockCable.CableEnum.TIN.metadata()))
				.save(cables);
		new ShapedBuilder<>()
				.name("gold")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("GGG")
				.define('G', "ingotGold")
				.withResult(new ItemStack(TRBlocks.cable, 12, BlockCable.CableEnum.GOLD.metadata()))
				.save(cables);
		new ShapedBuilder<>()
				.name("hv")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("III")
				.define('I', "ingotRefinedIron")
				.withResult(new ItemStack(TRBlocks.cable, 12, BlockCable.CableEnum.HV.metadata()))
				.save(cables);
		new ShapedBuilder<>()
				.name("insulated_copper")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("RRR")
				.pattern("CCC")
				.pattern("RRR")
				.define('C', "ingotCopper")
				.define('R', "itemRubber")
				.withResult(new ItemStack(TRBlocks.cable, 6, BlockCable.CableEnum.INSULATEDCOPPER.metadata()))
				.save(cables);
		new ShapedBuilder<>()
				.name("insulated_copper_v")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("RCR")
				.pattern("RCR")
				.pattern("RCR")
				.define('C', "ingotCopper")
				.define('R', "itemRubber")
				.withResult(new ItemStack(TRBlocks.cable, 6, BlockCable.CableEnum.INSULATEDCOPPER.metadata()))
				.save(cables);
		new ShapelessBuilder<>()
				.name("insulated_copper_wrap")
				.withCondition(IC2Condition.DeduplicateCondition())
				.requires(new ItemStack(TRBlocks.cable, 1, BlockCable.CableEnum.COPPER.metadata()))
				.requires("itemRubber")
				.withResult(new ItemStack(TRBlocks.cable, 1, BlockCable.CableEnum.INSULATEDCOPPER.metadata()))
				.save(cables);
		new ShapedBuilder<>()
				.name("insulated_gold")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("RRR")
				.pattern("GGG")
				.pattern("RRR")
				.define('G', "ingotGold")
				.define('R', "itemRubber")
				.withResult(new ItemStack(TRBlocks.cable, 4, BlockCable.CableEnum.INSULATEDGOLD.metadata()))
				.save(cables);
		new ShapelessBuilder<>()
				.name("insulated_gold_wrap")
				.withCondition(IC2Condition.DeduplicateCondition())
				.requires(new ItemStack(TRBlocks.cable, 1, BlockCable.CableEnum.GOLD.metadata()))
				.requires("itemRubber")
				.withResult(new ItemStack(TRBlocks.cable, 1, BlockCable.CableEnum.INSULATEDGOLD.metadata()))
				.save(cables);
		new ShapedBuilder<>()
				.name("insulated_hv")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("RRR")
				.pattern("III")
				.pattern("RRR")
				.define('I', "ingotRefinedIron")
				.define('R', "itemRubber")
				.withResult(new ItemStack(TRBlocks.cable, 4, BlockCable.CableEnum.INSULATEDHV.metadata()))
				.save(cables);
		new ShapelessBuilder<>()
				.name("insulated_hv_wrap")
				.withCondition(IC2Condition.DeduplicateCondition())
				.requires(new ItemStack(TRBlocks.cable, 1, BlockCable.CableEnum.HV.metadata()))
				.requires("itemRubber")
				.withResult(new ItemStack(TRBlocks.cable, 1, BlockCable.CableEnum.INSULATEDHV.metadata()))
				.save(cables);
		new ShapedBuilder<>()
				.name("glass_fiber_1")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("GGG")
				.pattern("RDR")
				.pattern("GGG")
				.define('G', "blockGlass")
				.define('R', "dustRedstone")
				.define('D', new ListIngredient()
						.addIngredient(new OreDictIngredient("gemDiamond", 1))
						.addIngredient(new OreDictIngredient("dustDiamond", 1)))
				.withResult(new ItemStack(TRBlocks.cable, 4, BlockCable.CableEnum.GLASSFIBER.metadata()))
				.save(cables);
		new ShapedBuilder<>()
				.name("glass_fiber_2")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("GGG")
				.pattern("RDR")
				.pattern("GGG")
				.define('G', "blockGlass")
				.define('R', "dustRedstone")
				.define('D', new ListIngredient()
						.addIngredient(new OreDictIngredient("gemRuby", 1))
						.addIngredient(new OreDictIngredient("dustRuby", 1)))
				.withResult(new ItemStack(TRBlocks.cable, 3, BlockCable.CableEnum.GLASSFIBER.metadata()))
				.save(cables);
		new ShapedBuilder<>()
				.name("glass_fiber_3")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("GGG")
				.pattern("RDR")
				.pattern("GGG")
				.define('G', "blockGlass")
				.define('R', "ingotSilver")
				.define('D', new ListIngredient()
						.addIngredient(new OreDictIngredient("gemDiamond", 1))
						.addIngredient(new OreDictIngredient("dustDiamond", 1)))
				.withResult(new ItemStack(TRBlocks.cable, 6, BlockCable.CableEnum.GLASSFIBER.metadata()))
				.save(cables);
		new ShapedBuilder<>()
				.name("glass_fiber_4")
				.withCondition(IC2Condition.DeduplicateCondition())
				.pattern("GGG")
				.pattern("RDR")
				.pattern("GGG")
				.define('G', "blockGlass")
				.define('R', "ingotElectrum")
				.define('D', new ListIngredient()
						.addIngredient(new OreDictIngredient("gemDiamond", 1))
						.addIngredient(new OreDictIngredient("dustDiamond", 1)))
				.withResult(new ItemStack(TRBlocks.cable, 8, BlockCable.CableEnum.GLASSFIBER.metadata()))
				.save(cables);
	}
}
